# Nixpacks configuration for Railway deployment
[phases.setup]
nixPkgs = ["python311", "nodejs_18", "gcc"]

[phases.install]
cmds = [
    "cd backend && pip install -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build"
]

[start]
cmd = "cd backend && python -m uvicorn main_sqlite:app --host 0.0.0.0 --port $PORT"