# nixpacks.toml
[phases.setup]
nixPkgs = ["python311", "nodejs_18", "gcc"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip",
    ". /opt/venv/bin/activate && pip install -r requirements.txt",
    "cd frontend && npm ci"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = ". /opt/venv/bin/activate && cd backend && python -m uvicorn main_sqlite:app --host 0.0.0.0 --port $PORT"